name: voici
channels:
  - conda-forge
dependencies:
  - python=3.11
  - xeus-python
  - pandas
  - folium
  - geopandas
  - pyproj
  - shapely
  - fiona
  - rtree
  - branca
  - ipywidgets
  - jupyterlab
